[package]
name = "lnp_node"
description = "LNP node"
version = "0.1.0-alpha.2"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
license = "MIT"
keywords = ["bitcoin", "node", "lightning-network", "smart-contracts", "rgb"]
edition = "2018"
readme = "README.md"
build = "build.rs"

[[bin]]
name = "connectiond"
required-features = ["server"]

[[bin]]
name = "lnp-cli"
required-features = ["cli"]

[dependencies]
# Rust language
amplify = "~1.2.0"
amplify_derive = "~1.2.0"
lazy_static = "~1.4.0"
# Bitcoin
electrum-client = { version = "=0.3.0-beta.1", optional = true }
# Serialization & parsing
serde_crate = { package = "serde", version = "~1.0.106", features = ["derive"], optional = true }
serde_with = { version = "~1.5.0", optional = true }
serde_json = { version = "~1.0.55", optional = true }
serde_yaml = { version = "~0.8.13", optional = true }
toml = { version = "~0.5.6", optional = true }
bech32 = { version = "~0.7.2", optional = true }
base64 = { version = "~0.12.1", optional = true }
regex = { version = "~1.3.9", optional = true }
# Congig & logging
settings = { version = "~0.10.1", package = "config", optional = true }
configure_me = { version = "0.3.4", optional = true }
dotenv = { version = "~0.15.0", optional = true }
clap = { version = "=3.0.0-beta.2", optional = true }
log = { version = "~0.4.8", optional = true, features = ["max_level_trace", "release_max_level_debug"] }
env_logger = { version = "~0.7.1", optional = true }
# Processes & IPC
async-trait = { version = "~0.1.35", optional = true }
tokio = { version = "~0.2.21", features = ["full"], optional = true }
zmq = { version = "~0.9.2", optional = true }

[dependencies.lnpbp]
git = "https://github.com/LNP-BP/rust-lnpbp"
branch = "v0.2"
features = ["lnp", "keygen", "tokio", "serde", "tor", "url", "websockets"]

[dependencies.lnpbp_derive]
git = "https://github.com/LNP-BP/rust-lnpbp"
branch = "v0.2"

[dependencies.lnpbp_services]
git = "https://github.com/LNP-BP/rust-lnpbp"
branch = "v0.2"

[build-dependencies]
clap = "=3.0.0-beta.2"
clap_generate = "=3.0.0-beta.2"
amplify = "~1.2.0"
lnpbp = { git = "https://github.com/LNP-BP/rust-lnpbp", branch = "v0.2", features = ["lnp", "keygen", "tokio", "serde", "tor", "url", "websockets"] }
configure_me_codegen = "0.3.14"

[patch.crates-io]
# We need this b/c of breaking change in tagged hash type generation
bitcoin_hashes = { git = "https://github.com/LNP-BP/bitcoin_hashes", tag = "lnpbp-v0.1.0-rc1" }
bitcoin = { git = "https://github.com/LNP-BP/rust-bitcoin", tag = "lnpbp-v0.1.0-rc1" }
# We need custom branches here just to depend on the same bitcoin master and do
# not have secp256k1 version conflict
miniscript = { git = "https://github.com/LNP-BP/rust-miniscript", tag = "lnpbp-v0.1.0-rc1" }
# Remove this once https://github.com/jean-airoldie/zeromq-src-rs/pull/15 got merged
zeromq-src = { git = "https://github.com/LNP-BP/zeromq-src-rs", branch = "fix/cmake" }

# Recommended set of features:
# 1. Standalone node: `server` (=`node`+`shell`)
# 2. Cli to remote node: `cli` (auto includes `shell` and `integration`)
# 3. Mobile app talking to a server: `client`
# 4. Mobile app with embedded node: `embedded` (auto includes `client` + `node`)
# 5. Simple cli utility app: `shell`
[features]
# Server is a standalone application that runs daemon
server = ["node", "shell"]
# Feature is required for any applications that talks to daemon processes
client = ["zmq"]
# Embedded is an app that contains ndoe in itself and that talks to it through
# integration layer
embedded = ["client", "node"]
# Command-line application feature
cli = ["shell", "client"]
# Required for all apps that can be launched from command-line shell as binaries
# (i.e. both servers and cli)
shell = [
    "dotenv", "clap", "settings", "configure_me", "log", "env_logger",
    "amplify/parse_arg", "serde"
]
# Besides server node can be run as a part of mobile app
# and other types of clients; thus `server` != `node`.
# This feature results in building with features not required for CLI
node = ["serde", "lnpbp/keygen", "tokio", "zmq"]
serde = ["serde_crate", "serde_with", "amplify/serde", "lnpbp/serde", "toml"]

[package.metadata.configure_me]
spec = "config_spec.toml"
