[package]
name = "lnp_node"
description = "LNP node"
version = "0.1.0-alpha.2"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
license = "MIT"
keywords = ["bitcoin", "node", "lightning-network", "smart-contracts", "rgb"]
edition = "2018"
readme = "README.md"

[[bin]]
name = "connectiond"
required-features = []

[[bin]]
name = "lnp-cli"
required-features = []

[dependencies]
# Rust language
amplify = "~1.2.0"
amplify_derive = "~1.2.0"
lazy_static = "~1.4.0"
# Bitcoin
electrum-client = "=0.3.0-beta.1"
# Serialization & parsing
serde = { version = "~1.0.111", features = ["derive"] }
serde_with = "~1.5.0"
serde_json = { version = "~1.0.55", optional = true }
serde_yaml = { version = "~0.8.13", optional = true }
toml = { version = "~0.5.6", optional = true }
bech32 = { version = "~0.7.2", optional = true }
base64 = { version = "~0.12.1", optional = true }
regex = { version = "~1.3.9", optional = true }
# Congig
settings = { version = "~0.10.1", package = "config", optional = true }
dotenv = { version = "~0.15.0", optional = true }
clap = { version = "=3.0.0-beta.2", optional = true }
# Logging
log = { version = "~0.4.8", optional = true, features = ["max_level_trace", "release_max_level_debug"] }
# Processes & IPC
async-trait = "~0.1.35"
tokio = { version = "~0.2.21", features = ["full"] }
zmq = "~0.9.2"

[dependencies.lnpbp]
git = "https://github.com/LNP-BP/rust-lnpbp"
branch = "v0.2"
features = ["lnp", "keygen", "tokio", "serde", "tor", "url", "websockets"]

[dependencies.lnpbp_derive]
git = "https://github.com/LNP-BP/rust-lnpbp"
branch = "v0.2"

[dependencies.lnpbp_services]
git = "https://github.com/LNP-BP/rust-lnpbp"
branch = "v0.2"

[patch.crates-io]
# We need this b/c of breaking change in tagged hash type generation
bitcoin_hashes = { git = "https://github.com/LNP-BP/bitcoin_hashes", tag = "lnpbp-v0.1.0-rc1" }
bitcoin = { git = "https://github.com/LNP-BP/rust-bitcoin", tag = "lnpbp-v0.1.0-rc1" }
# We need custom branches here just to depend on the same bitcoin master and do
# not have secp256k1 version conflict
miniscript = { git = "https://github.com/LNP-BP/rust-miniscript", tag = "lnpbp-v0.1.0-rc1" }
# Remove this once https://github.com/jean-airoldie/zeromq-src-rs/pull/15 got merged
zeromq-src = { git = "https://github.com/LNP-BP/zeromq-src-rs", branch = "fix/cmake" }

[features]
default = ["log"]